# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Gender.create(sex: '남자')
Gender.create(sex: '여자')
Category.create(movie_category: '드라마')
Category.create(movie_category: '액션')
Category.create(movie_category: '스릴러')
Category.create(movie_category: '공포')
Category.create(movie_category: '범죄')
Category.create(movie_category: '판타지')
Category.create(movie_category: '애니메이션')
Category.create(movie_category: '전쟁')
Category.create(movie_category: '코미디')
Category.create(movie_category: '멜로')
Category.create(movie_category: '미스터리')
Category.create(movie_category: 'SF')
Category.create(movie_category: '사극')
Category.create(movie_category: '다큐멘터리')
Category.create(movie_category: '뮤지컬')
Category.create(movie_category: '성인물')
Category.create(movie_category: '기타')
Weather.create(name: '봄')
Weather.create(name: '여름')
Weather.create(name: '가을')
Weather.create(name: '겨울')
Location.create(name: '경기/서울/인천')
Location.create(name: '대전/충남')
Location.create(name: '충북')
Location.create(name: '경남/부산/울산')
Location.create(name: '경북')
Location.create(name: '강원')
Location.create(name: '전남/광주')
Location.create(name: '전북')
Location.create(name: '제주')
