# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Gender.create(sex: '남자')
Gender.create(sex: '여자')
Category.create(movie_category: '드라마')
Category.create(movie_category: '액션')
Category.create(movie_category: '스릴러')
Category.create(movie_category: '공포')
Category.create(movie_category: '범죄')
Category.create(movie_category: '판타지')
Category.create(movie_category: '애니메이션')
Category.create(movie_category: '전쟁')
Category.create(movie_category: '코미디')
Category.create(movie_category: '멜로')
Category.create(movie_category: '미스터리')
Category.create(movie_category: 'SF')
Category.create(movie_category: '사극')
Category.create(movie_category: '다큐멘터리')
Category.create(movie_category: '뮤지컬')
Category.create(movie_category: '성인물')
Category.create(movie_category: '기타')
Job.create(name: '학생')
Job.create(name: '관리자')
Job.create(name: '전문가')
Job.create(name: '사무직')
Job.create(name: '서비스업')
Job.create(name: '판매직')
Job.create(name: '농림어업 종사자')
Job.create(name: '기능직')
Job.create(name: '기계조작 및 조립종사자')
Job.create(name: '노무직')
Job.create(name: '군인')
Job.create(name: '기타')
Emotion.create(name: '흥분되는')
Emotion.create(name: '행복한')
Emotion.create(name: '기쁜')
Emotion.create(name: '느긋한')
Emotion.create(name: '평화로운')
Emotion.create(name: '차분한')
Emotion.create(name: '졸린')
Emotion.create(name: '지루한')
Emotion.create(name: '슬픈')
Emotion.create(name: '긴장된')
Emotion.create(name: '화난')
Emotion.create(name: '짜증나는')
Bulletin.create(title: '공지사항', post_type: 'bulletin')
Bulletin.create(title: '자유게시판', post_type: 'bulletin')
Bulletin.create(title: '질문과답변', post_type: 'blog')
User.create(username: 'cjdtjcjdtj@gmail.com', password: 'h32326', age: 20, gender_id: 1, job_id: 1, emotion_id: 1, category_id: 1)
User.create(username: 'a@a.com', password: 'h32326', age: 30, gender_id: 2, job_id: 1, emotion_id: 1, category_id: 1)
User.create(username: 'a@b.com', password: 'h32326', age: 40, gender_id: 1, job_id: 3, emotion_id: 4, category_id: 5)
User.create(username: 'a@c.com', password: 'h32326', age: 50, gender_id: 1, job_id: 5, emotion_id: 6, category_id: 7)
User.create(username: 'a@d.com', password: 'h32326', age: 60, gender_id: 2, job_id: 2, emotion_id: 3, category_id: 8)
Bulletin.first.posts.create(title: '공지사항입니다.', content: '새 홈피를 단장하였습니다.', user_id: 1)
Bulletin.second.posts.create(title: '자유게시판입니다.', content: '재미있게', user_id: 1)
Bulletin.second.posts.create(title: '노잼입니다.', content: '...영화가 다 노잼', user_id: 1)
Bulletin.second.posts.create(title: '이거 추천 ㅋㅋㅋㅋㅋㅋ제댈됨?', content: '난 잘 모르겠는데', user_id: 1)
Bulletin.last.posts.create(title: '우와?', content: '신기해요', user_id: 1)